#!/bin/bash
# Michael Pratt <pratt@hablarmierda.net>
# $HOME/.bashrc

# First of all lets use vi mode :D!
set -o vi

# Configuration vars
export TERM=xterm-256color
export HISTSIZE=40000
export HISTFILESIZE=40000
export HISTTIMEFORMAT="%Y/%m/%d %H:%M "
export HISTIGNORE="&:ls:su:cat:man:cd:cp:mv:exit:clear:history"
export HISTCONTROL=ignoreboth # erasedups & ignorespace

# Tweak Some Bash Stuff
shopt -s cdspell # Correct the typos in the cd command 
shopt -s dirspell # Attempts spelling correction on directory names during word completion
shopt -s histappend # The history list is appended when the shell exits, rather than overwriting the file
shopt -s extglob # Allow extended globs! For example 'rm !(*.jpg|*.gif|*.png)'
shopt -s nocaseglob # Matches filenames in a case-insensitive fashion when performing filename expansion
shopt -s checkwinsize # Checks the window size after each command and, if necessary, updates the values of LINES and COLUMNS.

# GCC tweaks
if [[ "$(uname -m)" == "x86_64" ]]; then
    CHOST="x86_64-pc-linux-gnu"
    CFLAGS="-march=core2 -O2 -pipe"
elif [[ "$(uname -a | grep -i celeron)" ]]; then
    CHOST="i686-pc-linux-gnu"
    CFLAGS="-march=pentium-m -O2 -pipe -fomit-frame-pointer"
fi
CXXFLAGS="${CFLAGS}"

# Prompt
function __exit_prompt_status {
    EXITSTATUS="$?"
    BOLD="\e[\033[1m\]"
    RED="\e[\033[0;31m\]"
    OFF="\e[\033[m\]"
    if [ "${EXITSTATUS}" -ne 0 ]; then
        echo -ne "[$(tput bold && tput setaf 1):/$(tput sgr0)]"
    fi
}

PROMPT_COMMAND=__exit_prompt_status
[ "$(whoami)" = "root" ] && PS1="\u@\h:\w\$ " || PS1="[\u@\h \W]⚡ "

# Setup default editor
EDITORS="vim vi pico nano"
for ED in ${EDITORS}; do
    if [ -x "$(which $ED 2>/dev/null)" ]; then
        export EDITOR="$ED"
        export VISUAL="$EDITOR"
        break
    fi
done
unset EDITORS
unset ED

# Non root alias
if [ "$(whoami)" != "root" ]; then
   alias su="su -l"
fi

# Enable X for console apps launched by root!
if [ "$(whoami)" = "root" ] && [ -n "$(who | awk '{print $1}' | uniq | grep pratt)" ] && [ -e "/home/pratt/.Xauthority" ]; then
   xauth merge /home/pratt/.Xauthority
   export DISPLAY=:0.0
fi

# Source aliases, functions and stuff
if [ -e "$HOME/.shells.custom" ]; then
   . $HOME/.shells.custom
fi
