#!/bin/bash
# Michael Pratt <pratt@hablarmierda.net>
# $HOME/.zshrc

# Colors
autoload -U colors
colors 

# Lets set some options
autoload -U compinit
compinit

# Shell Options
#setopt ignoreeof           # ignore EOF ('^D') (i.e. don't log out on it)
#setopt noclobber            # don't overwrite existing files w/ > output redir
setopt braceccl             # {a-d} expands to a b c d
setopt hist_allow_clobber   # C-p or UP and command has >| now, ready to go
setopt autocd               # automatically cd to a directory if not cmd
setopt autopushd            # automatically pushd directories on dirstack
setopt nopushdsilent        # print dirstack after each cd/pushd
setopt pushdignoredups      # don't push dups on stack
setopt pushdminus           # pushd -N goes to Nth dir in stack
export DIRSTACKSIZE=8
setopt autonamedirs         # % export h=/home/sjs; cd ~h; pwd => /home/sjs
setopt cdablevars           # blah=~/media/movies; cd blah; pwd => ~/media/movies
setopt correct              # try to correct spelling...
setopt no_correctall        # ...only for commands, not filenames
setopt no_listbeep          # don't beep on ambiguous listings
setopt listpacked           # variable col widths (takes up less space)
setopt extendedglob         # use extended globbing (#, ~, ^)
export HISTFILE=~/.zsh-histfile
export HISTSIZE=5000
export SAVEHIST=5000
setopt incappendhistory
setopt sharehistory
setopt extendedhistory
setopt extendedhistory      # save timestamps in history
setopt no_histbeep          # don't beep for erroneous history expansions
setopt histignoredups       # ignore consecutive dups in history
setopt histfindnodups       # backwards search produces diff result each time
setopt histreduceblanks     # compact consecutive white space chars (cool)
setopt histnostore          # don't store history related functions
setopt incappendhistory     # incrementally add items to HISTFILE
setopt longlistjobs         # list jobs in long format
setopt promptsubst          # allow paramater, command, so on in prompt
setopt transient_rprompt    # hide RPROMPT after cmdline is executed
setopt no_beep          # don't beep on errors (in ZLE)
setopt auto_resume
setopt completeinword

# Prompt with git support
autoload -Uz vcs_info
zstyle ':vcs_info:*' stagedstr '%F{28}●'
zstyle ':vcs_info:*' unstagedstr '%F{11}●'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{11}%r'
zstyle ':vcs_info:*' enable git svn
precmd () {
    if [[ -z $(git ls-files --other --exclude-standard 2> /dev/null) ]] {
        zstyle ':vcs_info:*' formats '%F{green}%b%c%u'
    } else {
        zstyle ':vcs_info:*' formats '%F{green}%b%c%u%F{red}●'
    }
    vcs_info
}
 
PROMPT='[%n@%m %F{yellow}%B%c%b ${vcs_info_msg_0_}%{$reset_color%}]⚡ ▶ '
 
# Set some ZSH auto complete options
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
zstyle ':completion:*:killall:*' command 'ps -u $USER -o cmd'

# Theme based on the AVIT ZSH Theme
# LS colors, made with http://geoff.greer.fm/lscolors/
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS='di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:'
export GREP_COLOR='1;33'

# Source aliases, functions and stuff
if [ -e "$HOME/.shells.custom" ]; then
   . $HOME/.shells.custom
fi
