" .vimrc
" Michael Pratt
" pratt@hablarmierda.net 
" http://www.michael-pratt.com

set nocompatible " Forget compatibility with Vi. Who cares. - Required by Vundle
filetype off     " required by Vundle

" On Windows, also use '.vim' instead of 'vimfiles'; this makes
" synchronization across (heterogeneous) systems easier.
if has("win32") || has("win64")
    set runtimepath^=$HOME/.vim
    set runtimepath+=$HOME/.vim/after
endif

" Setting up vim-plug as the package manager {{{
if !filereadable(expand("~/.vim/autoload/plug.vim"))
    echo "Installing vim-plug and plugins. Restart vim after finishing the process."
    silent call mkdir(expand("~/.vim/autoload", 1), 'p')
    execute "!curl -fLo ".expand("~/.vim/autoload/plug.vim", 1)." https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')

" Plugins
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/syntastic'
Plug 'skammer/vim-css-color'
Plug 'terryma/vim-expand-region'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'justinmk/vim-sneak'
Plug 'bling/vim-airline'
Plug 'Raimondi/delimitMate'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-fugitive'
Plug 'StanAngeloff/php.vim'
Plug 'nathanaelkane/vim-indent-guides', {'on': 'IndentGuidesEnable'}
Plug 'mattn/emmet-vim'
Plug 'PProvost/vim-ps1'
Plug 'scrooloose/nerdtree'
" Plug 'shawncplus/phpcomplete.vim'

" Colorschemes
Plug 'veloce/vim-aldmeris'
Plug 'endel/vim-github-colorscheme'
Plug 'sjl/badwolf'
Plug 'tomasr/molokai'

if has("unix")
    Plug 'Valloric/YouCompleteMe', {'do': './install.sh' }
endif

call plug#end()
filetype plugin indent on
syntax on

" Load custom settings
source ~/.vim/settings.vim
source ~/.vim/mappings.vim
source ~/.vim/commands.vim

" Load plugin settings
for fpath in split(globpath('~/.vim/local/settings', '*.vim'), '\n')
  exe 'source' fpath
endfor

" Load stuff only when the gui is running
if has("gui_running")
    "
endif

" Set the color scheme on Gvim
if filereadable(expand('~/.vim/bundle/vim-aldmeris/colors/aldmeris.vim'))
    colorscheme aldmeris
endif

" Common abbreviations
iabbrev lenght length

" Source ~/.vim/.vimrc.after if it exists. In order to allow overriding
if filereadable(expand("~/.vim/vimrc.after"))
  source ~/.vim/vimrc.after
endif
