" .vimrc
" Michael Pratt
" pratt@hablarmierda.net 
" http://www.michael-pratt.com

set nocompatible " Forget compatibility with Vi. Who cares. - Required by Vundle
filetype off     " required by Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

" Plugins
Plugin 'gmarik/vundle'
Plugin 'scrooloose/syntastic'
Plugin 'skammer/vim-css-color'
Plugin 'terryma/vim-expand-region'
Plugin 'kien/ctrlp.vim'
Plugin 'Glench/Vim-Jinja2-Syntax'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'justinmk/vim-sneak'
Plugin 'bling/vim-airline'
Plugin 'Raimondi/delimitMate'
Plugin 'mattn/emmet-vim'
Plugin 'tpope/vim-surround'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'paradigm/TextObjectify'
Plugin 'StanAngeloff/php.vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'nanotech/jellybeans.vim'
Plugin 'veloce/vim-aldmeris'
Plugin 'altercation/vim-colors-solarized'

if has("win32")
    Plugin 'Hackworth/vim-ps1'
endif

if has("unix")
    Plugin 'Valloric/YouCompleteMe'
endif

call vundle#end()
filetype plugin indent on
syntax on

" Load custom settings
source ~/.vim/settings.vim
source ~/.vim/mappings.vim
source ~/.vim/commands.vim

" Load plugin settings
for fpath in split(globpath('~/.vim/local/settings', '*.vim'), '\n')
  exe 'source' fpath
endfor

" Set the color scheme on Gvim
if has("gui_running")
    colorscheme aldmeris
endif

" Common abbreviations
iabbrev lenght length

" Source ~/.vim/.vimrc.after if it exists. In order to allow overriding
if filereadable(expand("~/.vim/vimrc.after"))
  source ~/.vim/vimrc.after
endif
