" .vimrc
" Michael Pratt
" pratt@hablarmierda.net 
" http://www.michael-pratt.com

set nocompatible " Forget compatibility with Vi. Who cares. - Required by Vundle
filetype off     " required by Vundle

" On Windows, also use '.vim' instead of 'vimfiles'; this makes
" synchronization across (heterogeneous) systems easier.
if has("win32") || has("win64")
    set runtimepath^=$HOME/.vim
    set runtimepath+=$HOME/.vim/after
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

" Plugins
Plugin 'gmarik/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'skammer/vim-css-color'
Plugin 'terryma/vim-expand-region'
Plugin 'Glench/Vim-Jinja2-Syntax'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'justinmk/vim-sneak'
Plugin 'bling/vim-airline'
Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-fugitive'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'StanAngeloff/php.vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'mattn/emmet-vim'
Plugin 'PProvost/vim-ps1'
" Plugin 'shawncplus/phpcomplete.vim'

" Colorschemes
Plugin 'veloce/vim-aldmeris'
Plugin 'endel/vim-github-colorscheme'
Plugin 'nanotech/jellybeans.vim'
Plugin 'sjl/badwolf'
Plugin 'tomasr/molokai'

if has("unix")
    Plugin 'Valloric/YouCompleteMe'
endif

call vundle#end()
filetype plugin indent on
syntax on

" Load custom settings
source ~/.vim/settings.vim
source ~/.vim/mappings.vim
source ~/.vim/commands.vim

" Load plugin settings
for fpath in split(globpath('~/.vim/local/settings', '*.vim'), '\n')
  exe 'source' fpath
endfor

" Load stuff only when the gui is running
if has("gui_running")
    "
endif

" Set the color scheme on Gvim
if filereadable(expand('~/.vim/bundle/vim-aldmeris/colors/aldmeris.vim'))
    colorscheme aldmeris
endif

" Common abbreviations
iabbrev lenght length

" Source ~/.vim/.vimrc.after if it exists. In order to allow overriding
if filereadable(expand("~/.vim/vimrc.after"))
  source ~/.vim/vimrc.after
endif
