#!/bin/bash
# Michael Pratt <pratt@hablarmierda.net>
# $HOME/.bashrc

# First of all lets use vi mode :D!
set -o vi

# Configuration vars
export TERM=xterm-256color
export HISTSIZE=40000
export HISTFILESIZE=40000
export HISTTIMEFORMAT="%Y/%m/%d %H:%M "
export HISTIGNORE="&:ls:su:cat:man:cd:cp:mv:exit:clear:history"
export HISTCONTROL=ignoreboth # erasedups & ignorespace

# Tweak Some Bash Stuff
shopt -s cdspell # Correct the typos in the cd command 
shopt -s dirspell # Attempts spelling correction on directory names during word completion
shopt -s histappend # The history list is appended when the shell exits, rather than overwriting the file
shopt -s extglob # Allow extended globs! For example 'rm !(*.jpg|*.gif|*.png)'
shopt -s nocaseglob # Matches filenames in a case-insensitive fashion when performing filename expansion
shopt -s checkwinsize # Checks the window size after each command and, if necessary, updates the values of LINES and COLUMNS.

# GCC tweaks
if [[ "$(uname -m)" == "x86_64" ]]; then
    CHOST="x86_64-pc-linux-gnu"
    CFLAGS="-march=core2 -O2 -pipe"
elif [[ "$(uname -a | grep -i celeron)" ]]; then
    CHOST="i686-pc-linux-gnu"
    CFLAGS="-march=pentium-m -O2 -pipe -fomit-frame-pointer"
fi
CXXFLAGS="${CFLAGS}"

# Prompt
function __exit_prompt_status {
    EXITSTATUS="$?"
    BOLD="\e[\033[1m\]"
    RED="\e[\033[0;31m\]"
    OFF="\e[\033[m\]"
    if [ "${EXITSTATUS}" -ne 0 ]; then
        echo -ne "[$(tput bold && tput setaf 1):/$(tput sgr0)]"
    fi
}

PROMPT_COMMAND=__exit_prompt_status
[ "$(whoami)" = "root" ] && PS1="\u@\h:\w\$ " || PS1="[\u@\h \W]⚡ "

# Setup default editor
EDITORS="vim vi pico nano"
for ED in ${EDITORS}; do
    if [ -x "$(which $ED 2>/dev/null)" ]; then
        export EDITOR="$ED"
        export VISUAL="$EDITOR"
        break
    fi
done
unset EDITORS
unset ED

# Easier directory change
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Other alias
alias :q="exit"
alias ls="ls -h --color=auto --group-directories-first"
alias lsoctal="ls -la | sed -e 's/--x/1/g' -e 's/-w-/2/g' -e 's/-wx/3/g' -e 's/r--/4/g' -e 's/r-x/5/g' -e 's/rw-/6/g' -e 's/rwx/7/g' -e 's/---/0/g'"
alias cp="cp -i"
alias mv="mv -i"
alias grep="grep --color"
alias nocomment="grep -Ev '^\s*(#|//|$)'"
alias screenoff="xset dpms force off"
alias phpunit="phpunit --verbose"
alias phpcheck="find ./ -iname \*.php | xargs -n 1 php -l"
alias makepass="openssl rand -base64 32"
alias servephp="php -S localhost:8000"
alias servepython="python -c 'import SimpleHTTPServer; SimpleHTTPServer.test()'"
alias regrep="egrep -R -iH -n"

# Allow php ctags
if [ -e "/mnt/data/Scripts/dotfiles/bin/ctags" ]; then
    alias ctags-php="/mnt/data/Scripts/dotfiles/bin/ctags -R --fields=+aimS --languages=php"
fi

# Non root alias
if [ "$(whoami)" != "root" ]; then
   alias su="su -l"
fi

# Enable X for console apps launched by root!
if [ "$(whoami)" = "root" ] && [ -n "$(who | awk '{print $1}' | uniq | grep pratt)" ] && [ -e "/home/pratt/.Xauthority" ]; then
   xauth merge /home/pratt/.Xauthority
   export DISPLAY=:0.0
fi

# Append custom PATH
[ -e "/mnt/data/Scripts/dotfiles/bin" ] && PATH=${PATH}:/mnt/data/Scripts/dotfiles/bin
[ -r "/mnt/data/Scripts/dotfiles/bin/functions.d/functions.sh" ] && source /mnt/data/Scripts/dotfiles/bin/functions.d/functions.sh

# Load Slackware specific files
if [ -e "/etc/slackware-version" ]; then
    [ -r "/mnt/data/Scripts/dotfiles/bin/functions.d/slackware.sh" ] && source /mnt/data/Scripts/dotfiles/bin/functions.d/slackware.sh
    [ -e "/mnt/data/Scripts/dotfiles/slackware/bin" ] && PATH=$PATH:/mnt/data/Scripts/dotfiles/slackware/bin
fi
